#!/usr/bin/env bash

if [ "${IMPL_RESOURCEPACK_CONTEXT_LOADED:-0}" = "1" ]; then
  return 0
fi
IMPL_RESOURCEPACK_CONTEXT_LOADED=1

IMPL_RESOURCEPACK_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IMPL_RESOURCEPACK_PROJECT_ROOT="$(cd "$IMPL_RESOURCEPACK_LIB_DIR/../.." && pwd)"

if [ -f "$IMPL_RESOURCEPACK_PROJECT_ROOT/.env" ]; then
  set -a
  # shellcheck disable=SC1091
  source "$IMPL_RESOURCEPACK_PROJECT_ROOT/.env"
  set +a
fi

ADOFAI_DIR="${ADOFAI_DIR:-$HOME/Library/Application Support/Steam/steamapps/common/A Dance of Fire and Ice}"
ADOFAI_MODS_DIR="${ADOFAI_MODS_DIR:-$ADOFAI_DIR/Mods}"
ADOFAI_MANAGED="${ADOFAI_MANAGED:-$ADOFAI_DIR/ADanceOfFireAndIce.app/Contents/Resources/Data/Managed}"

DOTNET_ROOT="${DOTNET_ROOT:-$HOME/.dotnet}"
DOTNET_ROOT_ARM64="${DOTNET_ROOT_ARM64:-$DOTNET_ROOT}"
DOTNET_EXE="${DOTNET_EXE:-$DOTNET_ROOT/dotnet}"

UNITY_MOD_MANAGER_DLL="${UNITY_MOD_MANAGER_DLL:-$ADOFAI_MANAGED/UnityModManager/UnityModManager.dll}"
HARMONY_DLL="${HARMONY_DLL:-$ADOFAI_MANAGED/UnityModManager/0Harmony.dll}"
UNITY_EXE="${UNITY_EXE:-/Applications/Unity/Hub/Editor/6000.3.10f1/Unity.app/Contents/MacOS/Unity}"
IMPL_RESOURCEPACK_UNITY_PROJECT="$IMPL_RESOURCEPACK_PROJECT_ROOT/ImplResourcePack.Unity"
IMPL_RESOURCEPACK_FONT_ASSETS="$IMPL_RESOURCEPACK_PROJECT_ROOT/ImplResourcePack/Assets/Font"

IMPL_RESOURCEPACK_BUILD_OUTPUT="${IMPL_RESOURCEPACK_BUILD_DIR:-$IMPL_RESOURCEPACK_PROJECT_ROOT/build/ImplResourcePack}"
IMPL_RESOURCEPACK_INSTALL_PATH="${IMPL_RESOURCEPACK_INSTALL_DIR:-$ADOFAI_MODS_DIR/ImplResourcePack}"

IMPL_RESOURCEPACK_PACKAGE_BUILD_ROOT="${IMPL_RESOURCEPACK_PACKAGE_ROOT:-$IMPL_RESOURCEPACK_PROJECT_ROOT/build/package}"
IMPL_RESOURCEPACK_PACKAGE_STAGE="$IMPL_RESOURCEPACK_PACKAGE_BUILD_ROOT/ImplResourcePack"
IMPL_RESOURCEPACK_PACKAGE_ZIP_PATH="${IMPL_RESOURCEPACK_PACKAGE_ZIP:-$IMPL_RESOURCEPACK_PROJECT_ROOT/build/ImplResourcePack.zip}"
IMPL_RESOURCEPACK_VERSION_ASSET_PATH="${IMPL_RESOURCEPACK_VERSION_ASSET:-$IMPL_RESOURCEPACK_PROJECT_ROOT/build/ImplResourcePack.version}"
IMPL_RESOURCEPACK_CHECKSUM_ASSET_PATH="${IMPL_RESOURCEPACK_CHECKSUM_ASSET:-$IMPL_RESOURCEPACK_PACKAGE_ZIP_PATH.sha256}"
IMPL_RESOURCEPACK_PLATFORM="$(uname -s)"

export IMPL_RESOURCEPACK_PROJECT_ROOT
export ADOFAI_DIR ADOFAI_MODS_DIR ADOFAI_MANAGED
export DOTNET_ROOT DOTNET_ROOT_ARM64 DOTNET_EXE
export UNITY_MOD_MANAGER_DLL HARMONY_DLL
export UNITY_EXE IMPL_RESOURCEPACK_UNITY_PROJECT IMPL_RESOURCEPACK_FONT_ASSETS
export IMPL_RESOURCEPACK_BUILD_OUTPUT IMPL_RESOURCEPACK_INSTALL_PATH
export IMPL_RESOURCEPACK_PACKAGE_BUILD_ROOT IMPL_RESOURCEPACK_PACKAGE_STAGE IMPL_RESOURCEPACK_PACKAGE_ZIP_PATH
export IMPL_RESOURCEPACK_VERSION_ASSET_PATH IMPL_RESOURCEPACK_CHECKSUM_ASSET_PATH
export IMPL_RESOURCEPACK_PLATFORM

is_macos() {
  [ "$IMPL_RESOURCEPACK_PLATFORM" = "Darwin" ]
}
